Pelumi/add mfa toggling to settings
sfbrigade/bats-server pull request #303
Opened 2023-06-15 19:08 UTC by olupelumi

2023-06-21 03:06 UTC, olupelumi commented on client/src/Admin/Settings.js
> +      .update(contextOrganization, organizationInEdit)
Decided to patch with the whole organization object as opposed to just the value of the `isMfaEnabled` value in order to allow for more organization settings to be updated in the future. 
This is what I meant in the description of "Set the groundwork for showing and updating more organization settings"

2023-06-22 03:07 UTC, francisli requested changes
Hi Pelumi, this looks great... can you resolve the conflicts that are now showing up (after I merged your previous PR)?

Also, I'm wondering if showing the editing form as a modal popup is needed- as we add more options, it might be limiting to lay everything out in it.

Instead, can we just enable the form in place in the page, showing the Submit/Cancel buttons?

2023-06-22 14:34 UTC, olupelumi commented on client/src/Admin/Settings.js
> +  }, [showEdit, organization]);
resetting the `organizationInEdit` when showEdit and organization is toggled such that it's always in sync with `organization` context when we close out of Edit mode without saving and for when we update the organization's info in our context.

2023-07-26 23:50 UTC, merged

2023-07-26 23:56 UTC, olupelumi commented
yay final piece merged