304 write e2e tests for 2fa
sfbrigade/bats-server pull request #306
Opened 2023-07-22 01:05 UTC by canjalal

E2E tests now test for 2FA authentication for EMS and Healthcare users, having the tests run serially rather than default in parallel so that the 2FA authentication codes are picked up sequentially by MailCatcher. Typos for "authorization code" were also fixed.

2023-08-02 20:33 UTC, francisli commented
@canjalal looking at the last CircleCi log, the tests are now running, but failing. So the config looks fine, but the tests themselves need to be confirmed...?

2023-08-02 22:50 UTC, francisli commented
@canjalal I've resolved the conflict on this branch with the latest on dev...

I also pulled down your branch, and ran the e2e tests locally, and I also get the errors seen on CircleCi. Do they actually pass when run on your computer?

2023-08-02 23:01 UTC, canjalal commented
> @canjalal I've resolved the conflict on this branch with the latest on dev...
> 
> I also pulled down your branch, and ran the e2e tests locally, and I also get the errors seen on CircleCi. Do they actually pass when run on your computer?

@francisli  yes they do pass on my computer

2023-08-02 23:12 UTC, francisli commented
@canjalal nevermind, my local test failures were related to the hardcoded mailcatcher hostname (localhost). since I'm running the tests inside the container, I've parameterized the tests so that they pull from the SMTP_HOST env var.

2023-08-02 23:51 UTC, francisli commented
@canjalal after logging in to CircleCI and doing some experimentation, I'm pretty sure that the test failures are caused by timing issues.

That is, after the username/password is entered, the script immediately hits mailcatcher to get the latest message. However, in the CircleCI container, this is happening _before_ the mail has been sent and received by the server. The script instead fetches an _older_ email with a no-longer-valid auth code.

To verify this, I added a line of code to clear all mail from mailcatcher before the log in occurs, and sure enough, the test fails now because it fetches an empty messages list from mailcatcher.

So, we need to put in some sort of delay/wait on fetching messages from mailcatcher. And, it would probably be best to put a before/after hook to clear mailcatcher before/after every test.

2023-08-03 00:00 UTC, francisli requested changes
Per previous comments, let's add hooks to clear mailcatcher before/after tests so we know each test starts from a clean slate.

Also, I notice you're hitting mailcatcher using fetch requests... you might also look into Playwright's classes for making API calls:

https://playwright.dev/docs/api-testing#sending-api-requests-from-ui-tests

Maybe there are some helpers in their implementation that might be useful? I.e. so that we can wait until mailcatcher returns a non-empty messages list...?

2023-08-08 06:48 UTC, canjalal commented
> essages from mailcatcher. And, it would probably be best to put a before/after hook to clear mailcatcher before/after every te

@francisli are you able to clear Mailcatcher without having to shut down and restart it? I'm curious how you did it, because the documentation that I'm reading seems to suggest you have to do that, and not sure how to do that within Docker.

2023-08-08 17:38 UTC, francisli commented
> > essages from mailcatcher. And, it would probably be best to put a before/after hook to clear mailcatcher before/after every te
> 
> @francisli are you able to clear Mailcatcher without having to shut down and restart it? I'm curious how you did it, because the documentation that I'm reading seems to suggest you have to do that, and not sure how to do that within Docker.

I actually went to the Mailcatcher source code to see the implementation of the REST API, and saw that you can issue a DELETE /messages http request to delete the inbox (this is probably the same call used when you hit the Clear button in the web UI): https://github.com/sj26/mailcatcher/blob/591eb16234e91aae4c3955ef9f0b33e30fbbd2dc/lib/mail_catcher/web/application.rb#L85

2023-08-10 00:56 UTC, canjalal commented on e2e/tests/home.spec.js
> +    await page.goto(`http://${process.env.SMTP_HOST}:1080/`);
@francisli when I parameterize the mail server like this, my tests fail locally. Does it work for you locally? If it doesn't, I'll make a ternary at the top to set the URL to `localhost` if the environment is `development`.

2023-08-15 07:45 UTC, canjalal commented on e2e/tests/home.spec.js
> +    expect(deleteRequest.ok()).toBeTruthy();
This seems to have passed, so I will be converting the `fetch` calls to implementations of `request`

2023-08-17 04:22 UTC, canjalal commented
> Per previous comments, let's add hooks to clear mailcatcher before/after tests so we know each test starts from a clean slate.
> 
> Also, I notice you're hitting mailcatcher using fetch requests... you might also look into Playwright's classes for making API calls:
> 
> https://playwright.dev/docs/api-testing#sending-api-requests-from-ui-tests
> 
> Maybe there are some helpers in their implementation that might be useful? I.e. so that we can wait until mailcatcher returns a non-empty messages list...?

Alright, ready for second review, @francisli

2023-08-17 20:35 UTC, canjalal commented on server/seeders/20201203021903-users-seed.js
> +      );
Add an user whose organization, AMR uses 2FA

2023-08-17 20:36 UTC, canjalal commented on server/seeders/20201109034858-organizations-seed.js
> +        insert into organization (organizationname, organizationtypeenum, organizationstate, organizationstateuniqueid, recordcreatetimestamp, recordcreateuser_uuid, recordupdatetimestamp, recordupda
Now that 2FA is disabled by default, I am re-enabling it on the AMR organization so that we can test 2FA

2023-08-17 20:39 UTC, canjalal commented on server/views/auth/local/twoFactor.ejs
> +        <h3>Please enter the Authorization Code that was sent to your E-mail</h3>
fix typo

2023-08-18 21:25 UTC, merged