Add pre-filled dropdowns for Unit # and Incident # form fields
sfbrigade/bats-server pull request #61
Opened 2021-06-03 05:20 UTC by julianmclain

WIP

2021-06-03 05:22 UTC, julianmclain commented
@abmcbride5 I added the routes for the 2 new API endpoints. Right now they just return a hard-coded example representing the format that the front-end should expect.

2021-06-05 00:04 UTC, julianmclain commented
@abmcbride5 I finished the API routes and decided to change the placeholder implementation a bit. From a front-end perspective, there's 2 new `ApiService` methods. Here's example usage / response data:
```
ApiService.ambulances.getIdentifiers()

{
  "ambulanceIdentifiers": [
    "SFFD-1",
    "SFFD-2",
    "SFFD-3",
    "SFFD-4"
  ]
}
```

and 

```
ApiService.emsCalls.getDispatchCallNumbers('SFFD-1')

{
  "dispatchCallNumbers": [
    1
  ]
}
```
Right now our backend terminology is a bit different than the front end. `ambulanceIdentifier` is `Unit Number` and `dispatchCallNumber` is `Incident Number`.

2021-06-05 00:13 UTC, julianmclain commented
Also I added a new seed file for us to use in local testing. You can add the data to your local database by opening a bash session inside the running docker container and running `sequelize db:seed --seed 20210604221937-ems-call-ambulances-seed.js`

2021-07-18 16:43 UTC, francisli commented
There's still more review I'd like to do on this PR, but I've just pushed up a change... minor change to rename ComboBox to FormComboBox to match the other Form* components...

But a bigger change to also import the actual ComboBox component javascript from USWDS and enable it on the component- otherwise, it just functions as a standard drop-down select box. This is documented here: https://designsystem.digital.gov/documentation/developers/#js-customization

I put a ref on a parent div around the markup, which I can then use to pass the element into the USWDS component initializer, enabling the combobox functionality...

Will find some more time later to do more testing and code cleanup...

2021-07-18 16:43 UTC, francisli commented on src/Components/FormComboBox.js
> +import { comboBox } from '../../node_modules/uswds/src/js/components';
Here you see where I import the USWDS comboBox component...

2021-07-18 16:44 UTC, francisli commented on src/Components/FormComboBox.js
> +    comboBox.on(current);
Here's where we "turn on" the comboBox interactivity...

2021-07-18 16:48 UTC, francisli requested changes
If you have time to look at some of the review comments, feel free to jump in and push up more changes... otherwise, I'll find some time to do a final cleanup pass before we next meet...

2021-07-18 16:48 UTC, francisli commented on src/EMS/PatientFields.js
> +  function createOptionsList(listName, listInfo) {
This function can definitely be refactored- if we're passing in the list itself, and the list objects have a consistent object structure (i.e. they each have an "id", etc), then we shouldn't need to pass in a listName and check on it- notice how the code is almost identical between the two if statements? Doesn't listInfo == ambulanceId and listInfo==dispatchCall depending upon what is being passed in?

2021-07-18 16:48 UTC, francisli commented on src/EMS/PatientFields.js
> +  const [dispatchCall, setDispatchCall] = useState([]);
These names, ambulanceId and dispatchCall, are misleading- they sound like singleton objects, but they actually store arrays, a _collection_ of objects.

2021-07-18 22:18 UTC, francisli commented on src/EMS/PatientFields.js
> +  const [dispatchCall, setDispatchCall] = useState([]);
I've renamed these to be plural

2021-07-18 22:19 UTC, francisli commented on src/EMS/PatientFields.js
> +  function createOptionsList(listName, listInfo) {
I've refactored/simplified the code...

2021-07-19 18:53 UTC, francisli approved these changes
Good work on getting the base component and implementation up and running for this...

I've finished off enabling/adding more of the ComboBox functionality myself, which was a bit tricky since the USWDS ComboBox component adds a bunch of custom elements outside of React, so standard DOM methods had to be used to tie into its behavior...

I think this is working well now, so I'm going to merge in and deploy- but let's all definitely test and make sure there aren't any wierd bugs with this custom implementation...

2021-07-19 18:53 UTC, francisli commented on src/Components/FormComboBox.js
> +  const [customOption, setCustomOption] = useState(null);
I've added some additional state to support allowing the user to input a new value that is not in the options list, that I call the "customOption". This did not seem to be a part of the default USWDS comboBox functionality.

2021-07-19 18:53 UTC, francisli commented on src/Components/FormComboBox.js
> +    input.value = value;
Here we do a bunch of custom initialization on the input box added by USWDS for the comboBox. We have to use standard DOM methods in this case...

2021-07-19 18:53 UTC, francisli commented on src/Components/FormComboBox.js
> +  }, [validationState]);
Changing the classes on the select element after comboBox initialization seemed to screw things up- so here I add another useEffect that watches the validationState and manually adds/removes the validation state from the custom input box added by the USWDS combobox component- again, we have to use standard DOM methods in this case...

2021-07-19 18:53 UTC, francisli commented on src/Components/FormComboBox.js
> +  }
This code from lines ~45-60 checks if the user has typed in something that doesn't exist in the options list, and creates a new combined options list with that customOption at the beginning.

2021-07-19 18:53 UTC, francisli commented on src/Components/FormComboBox.js
> +      <ValidationMessage validationState={validationState} />
Made sure to add in all the ValidationMessage handling...

2021-07-19 18:53 UTC, merged