Polish Patient Info
sfbrigade/bats-server pull request #76
Opened 2021-07-28 09:27 UTC by kunal-rp

add input ranges for patient info fields

2021-07-28 09:28 UTC, kunal-rp commented
<img width="518" alt="Screen Shot 2021-07-28 at 2 19 14 AM" src="https://user-images.githubusercontent.com/17953739/127298962-67de487a-4dcf-4c4f-bb41-e54d1f0dec76.png">

2021-07-29 00:09 UTC, francisli requested changes
Hi! Thanks for this contribution... I wonder if we can move the INPUT_RANGES out of the component itself to somewhere related to those specific properties (Ringdown, or PatientFields...?) and pass them in through props to make the component more generic...

Also, I think we'd need to expand the BP ranges (at least, drop the min numbers).

Not sure if we always want to default to showing the min value as the placeholder, I think it might be more distracting- something to ask the UX team about...?

2021-07-29 07:19 UTC, kunal-rp commented
updated changes. Rm placeholder for now, can circle back after UX review

2021-08-05 00:54 UTC, francisli requested changes

2021-08-05 00:54 UTC, francisli commented on src/EMS/PatientFields.js
> +  diastolicBloodPressure: {min: 80 , max: 120},
Let's set the min for systolic to be 90 and the min for diastolic to be 60... if a responder takes a measurement, and it's normal, I think they should still be able to record it...?

2021-08-11 21:12 UTC, francisli approved these changes
I went ahead and made the changes to the BP validation ranges, and ran the pretty printer, so I think this is good to go...

Also, I've invited you to the project (https://github.com/sfbrigade/bats-server/invitations), so next time you can open a new branch directly in the repo instead of forking... that way, your work will also be run in CI...!

2021-08-11 21:12 UTC, merged